### ISSUE TITLE
handler_type in SampleDescriptionBox (8.5.2.2) and SampleGroupDescriptionBox (8.9.3.2)

### ISSUE THREAD

**Issue by lkondrad** [MPEGGroup/FileFormat#28] opened 2021-04-19 08:50 UTC
Based on WG03N0148 (ISOBMFF 7th edition)

SampleDescriptionBox (8.5.2.2) and SampleGroupDescriptionBox (8.9.3.2) have handler_type as input to the class, but the handler_type is not store anywhere and there is no semantics for it. 

Is it a bug or is handler_type intentional there? If the latter then it would be probably good to have a clarification text. 

> aligned(8) class SampleDescriptionBox (unsigned int(32) handler_type) extends FullBox('stsd', version, 0){
&nbsp;&nbsp;int i ;
&nbsp;&nbsp;unsigned int(32) entry_count;
&nbsp;&nbsp;for (i = 1 ; i <= entry_count ; i++){
&nbsp;&nbsp;&nbsp;&nbsp;SampleEntry();		// an instance of a class derived from SampleEntry
&nbsp;&nbsp;}
}

> aligned(8) class SampleGroupDescriptionBox (unsigned int(32) handler_type) extends FullBox('sgpd', version, 0){
&nbsp;&nbsp;unsigned int(32) grouping_type;
&nbsp;&nbsp;if (version>=1) { unsigned int(32) default_length; }
&nbsp;&nbsp;if (version>=2) {
&nbsp;&nbsp;&nbsp;&nbsp;unsigned int(32) default_group_description_index;
&nbsp;&nbsp;}
&nbsp;&nbsp;unsigned int(32) entry_count;
&nbsp;&nbsp;int i;
&nbsp;&nbsp;for (i = 1 ; i <= entry_count ; i++){
&nbsp;&nbsp;&nbsp;&nbsp;if (version>=1) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (default_length==0) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;unsigned int(32) description_length;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;SampleGroupDescriptionEntry (grouping_type);
&nbsp;&nbsp;&nbsp;&nbsp;// an instance of a class derived from SampleGroupDescriptionEntry
&nbsp;&nbsp;&nbsp;&nbsp;//  that is appropriate and permitted for the media type
&nbsp;&nbsp;}
}

**Comment by cconcolato** [comment] 2021-04-21 18:48
Previous editions of ISOBMFF (e.g. 2012, 4th edition) used to have a switch on the handler to select a type of SampleEntry:
```
aligned(8) class SampleDescriptionBox (unsigned int(32) handler_type) extends FullBox('stsd', 0, 0){ 
  int i ; 
  unsigned int(32) entry_count; 
  for (i = 1 ; i <= entry_count ; i++){ 
    switch (handler_type){ 
    case ‘soun’: // for audio tracks 
      AudioSampleEntry(); 
      break;
    case ‘vide’: // for video tracks 
      VisualSampleEntry(); 
      break; 
    case ‘hint’: // Hint track 
      HintSampleEntry(); 
      break; 
    case ‘meta’: // Metadata track 
      MetadataSampleEntry(); 
      break;
    } 
  } 
 } 
 ```
I think this is left over and it could be removed.

**Comment by cconcolato** [comment] 2021-04-26 21:16
Note that this is a duplicate of https://github.com/MPEGGroup/FileFormat/issues/21

**Comment by dwsinger** [comment] 2021-07-19 22:28
Ficed in the 7th edition, closing

**Closed by dwsinger** 2021-07-19 22:28 UTC
Labels: ISOBMFF
